---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket creation to store Cost Optimization Reports
Resources:
  S3CostOptimizationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        !Join
          - ''
          - - 'costoptimization-'
            - Ref: AWS::AccountId
            - '-bucket'
Outputs:
  S3CostOptimizationBucket:
    Description: S3 bucket to store Cost Optimization Reports
    Value:
      Ref: S3CostOptimizationBucket
    Export:
      Name: S3CostOptimizationBucket